package secrets

import (
	"context"
	"crypto/rand"
	"database/sql"
	"errors"
	"fmt"

	"resy-snipe/internal/clock"
)

// SaltLen is the length in bytes of the per-deployment Argon2id salt
// stored in secrets_meta.kdf_salt. 32 bytes is overkill but matches
// the recommendation in docs/v2/design/secrets.md §Key derivation and
// makes a rainbow-table attack across deployments useless.
const SaltLen = 32

// Meta is the persistent context attached to the daemon's secrets
// world. There is exactly one Meta row per data.db (enforced by the
// CHECK (id = 1) constraint on the secrets_meta table). Callers
// read it once at boot via LoadOrInitMeta and pass it to NewSealer.
type Meta struct {
	// KDFSalt is the per-deployment Argon2id salt, 32 random bytes.
	// Generated by crypto/rand on first boot and never rotated except
	// by an explicit `secrets rotate` flow.
	KDFSalt []byte

	// ActiveVersion is the schema version of the active KDF/AEAD
	// envelope. Bumped by every successful rotate. Per-row mismatch
	// is the mixed-version refusal in M2-03.
	ActiveVersion int
}

// LoadOrInitMeta reads the singleton secrets_meta row, creating it
// idempotently on first boot. The salt is generated via crypto/rand
// the first time and stays the same on subsequent boots. The CHECK
// (id = 1) constraint means a second INSERT is a no-op via INSERT OR
// IGNORE; we then SELECT to recover the persisted row regardless of
// which branch ran.
//
// Migration 0002_v2_multi_user.sql created the table but deferred the
// row insert to seal-init time so the salt lives next to the code
// that consumes it (this package), not next to the DDL.
func LoadOrInitMeta(ctx context.Context, db *sql.DB, c clock.Clock) (Meta, error) {
	if db == nil {
		return Meta{}, errors.New("secrets: LoadOrInitMeta: nil db")
	}
	if c == nil {
		return Meta{}, errors.New("secrets: LoadOrInitMeta: nil clock")
	}

	salt := make([]byte, SaltLen)
	if _, err := rand.Read(salt); err != nil {
		return Meta{}, fmt.Errorf("secrets: generate salt: %w", err)
	}

	// INSERT OR IGNORE: on first boot the row lands; on every later
	// boot the CHECK (id = 1) + PRIMARY KEY rejects the duplicate and
	// we fall through to the SELECT below. crypto/rand was called
	// either way — we throw the spare salt away on the no-op path,
	// which is fine; salts aren't precious.
	if _, err := db.ExecContext(ctx, `
		INSERT OR IGNORE INTO secrets_meta (id, kdf_salt, active_version, created_at)
		VALUES (1, ?, 1, ?)`,
		salt, c.Now().UnixMilli(),
	); err != nil {
		return Meta{}, fmt.Errorf("secrets: insert meta: %w", err)
	}

	var got Meta
	if err := db.QueryRowContext(ctx,
		`SELECT kdf_salt, active_version FROM secrets_meta WHERE id = 1`,
	).Scan(&got.KDFSalt, &got.ActiveVersion); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return Meta{}, errors.New("secrets: meta row missing after upsert")
		}
		return Meta{}, fmt.Errorf("secrets: read meta: %w", err)
	}
	if len(got.KDFSalt) != SaltLen {
		return Meta{}, fmt.Errorf("secrets: meta salt length %d, want %d", len(got.KDFSalt), SaltLen)
	}
	return got, nil
}
